openapi: 3.0.1
info:
  title: Chainlens Account-Controller Account-Transactions-Controller API
  description: Chainlens provides a robust and intuitive platform combining user-friendly exploration with powerful analytics and advanced features. Whether monitoring real-time blockchain transactions, verifying smart contracts, or tracking NFTs, Chainlens ensures you have all the necessary tools at your fingertips.
  version: master
tags:
- name: Account-Transactions-Controller
paths:
  /accounts/{addressHash}/transactions:
    get:
      tags:
      - Account-Transactions-Controller
      summary: Chainlens Retrieve a transactions for an account.
      operationId: findAccountTransactions
      parameters:
      - name: addressHash
        in: path
        description: The account address.
        required: true
        schema:
          type: string
      - name: query
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/FindAddressTransactionsQuery'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/LatestTransactionModel'
components:
  schemas:
    FindAddressTransactionsQuery:
      required:
      - direction
      - page
      - size
      - sort
      type: object
      properties:
        page:
          minimum: 0
          type: integer
          format: int32
        size:
          maximum: 100
          minimum: 1
          type: integer
          format: int32
        direction:
          type: string
          enum:
          - ASC
          - DESC
        sort:
          type: string
          enum:
          - blockNumber
          - timestampISO
          - transactionType
          - functionName
          - direction
          - ethValue
        filter:
          type: string
    Link:
      required:
      - display
      - href
      - rel
      type: object
      properties:
        href:
          type: string
        rel:
          type: string
        display:
          type: string
    FunctionMeta:
      required:
      - functionName
      - params
      - stateMutability
      - type
      type: object
      properties:
        functionName:
          type: string
        stateMutability:
          type: string
        type:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/FunctionParameterModel'
    FunctionParameterModel:
      required:
      - name
      - type
      - value
      type: object
      properties:
        value:
          type: object
        name:
          type: string
        type:
          type: string
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
    LatestTransactionModel:
      required:
      - data
      - paging
      type: object
      properties:
        paging:
          $ref: '#/components/schemas/PagingModel'
        data:
          type: array
          items:
            $ref: '#/components/schemas/TransactionRowModel'
    AddressInfo:
      required:
      - address
      - isContract
      - isProxy
      - isVerified
      type: object
      properties:
        address:
          type: string
        name:
          type: string
        isContract:
          type: boolean
        isVerified:
          type: boolean
        isProxy:
          type: boolean
        verifiedStatus:
          type: string
          enum:
          - Partial
          - Full
        contractType:
          type: string
          enum:
          - contract
          - nft
          - token
    PagingModel:
      required:
      - direction
      - page
      - size
      - sort
      - totalElements
      type: object
      properties:
        page:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        sort:
          type: string
        direction:
          type: string
          enum:
          - ASC
          - DESC
        totalElements:
          type: integer
          format: int64
    TransactionRowModel:
      required:
      - direction
      - ethValue
      - from
      - fromAddressInfo
      - fromLinks
      - hash
      - isPrivate
      - timestampISO
      - to
      - toAddressInfo
      - toLinks
      - transactionType
      - value
      type: object
      properties:
        hash:
          type: string
        from:
          type: string
        fromAddressInfo:
          $ref: '#/components/schemas/AddressInfo'
        fromLinks:
          type: array
          items:
            $ref: '#/components/schemas/Link'
        to:
          type: string
        toAddressInfo:
          $ref: '#/components/schemas/AddressInfo'
        toLinks:
          type: array
          items:
            $ref: '#/components/schemas/Link'
        value:
          type: integer
        ethValue:
          type: number
        isPrivate:
          type: boolean
        timestampISO:
          type: string
        transactionType:
          type: string
          enum:
          - Transfer
          - ContractCreation
          - ContractCall
        status:
          type: string
        revertReason:
          type: string
        functionMeta:
          $ref: '#/components/schemas/FunctionMeta'
        direction:
          type: string
          enum:
          - In
          - Out
          - Self
          - Unknown
        isInternalToAccount:
          type: boolean
externalDocs:
  description: Chainlens Documentation
  url: https://docs.chainlens.com/
