openapi: 3.0.1
info:
  title: Chainlens Account-Controller Internal-Transactions-Controller API
  description: Chainlens provides a robust and intuitive platform combining user-friendly exploration with powerful analytics and advanced features. Whether monitoring real-time blockchain transactions, verifying smart contracts, or tracking NFTs, Chainlens ensures you have all the necessary tools at your fingertips.
  version: master
tags:
- name: Internal-Transactions-Controller
paths:
  /transactions/{transactionHash}/internal-transactions:
    get:
      tags:
      - Internal-Transactions-Controller
      summary: Chainlens Retrieve all internal transactions for this transaction.
      operationId: getInternalsByTx
      parameters:
      - name: transactionHash
        in: path
        description: The transaction hash identifying the transaction that contains the events.
        required: true
        schema:
          type: string
      - name: query
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/FindInternalTransactionsQuery'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/LatestInternalTransactionModel'
  /internal-transactions:
    get:
      tags:
      - Internal-Transactions-Controller
      summary: Chainlens Retrieve internal transactions by address.
      operationId: findTransactions_1
      parameters:
      - name: query
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/FindInternalTransactionsQuery'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/LatestInternalTransactionModel'
components:
  schemas:
    Link:
      required:
      - display
      - href
      - rel
      type: object
      properties:
        href:
          type: string
        rel:
          type: string
        display:
          type: string
    FunctionMeta:
      required:
      - functionName
      - params
      - stateMutability
      - type
      type: object
      properties:
        functionName:
          type: string
        stateMutability:
          type: string
        type:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/FunctionParameterModel'
    FunctionParameterModel:
      required:
      - name
      - type
      - value
      type: object
      properties:
        value:
          type: object
        name:
          type: string
        type:
          type: string
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
    InternalTransactionRowModel:
      required:
      - blockNumber
      - direction
      - ethValue
      - from
      - fromAddressInfo
      - fromLinks
      - id
      - input
      - parentHash
      - timestampISO
      - to
      - toAddressInfo
      - toLinks
      - transactionType
      - value
      type: object
      properties:
        parentHash:
          type: string
        blockNumber:
          type: integer
          format: int64
        id:
          type: string
        from:
          type: string
        fromAddressInfo:
          $ref: '#/components/schemas/AddressInfo'
        fromLinks:
          type: array
          items:
            $ref: '#/components/schemas/Link'
        to:
          type: string
        toAddressInfo:
          $ref: '#/components/schemas/AddressInfo'
        toLinks:
          type: array
          items:
            $ref: '#/components/schemas/Link'
        value:
          type: integer
        ethValue:
          type: number
        timestampISO:
          type: string
        input:
          type: string
        transactionType:
          type: string
          enum:
          - ContractCreation
          - ContractCall
          - Suicide
          - Other
        direction:
          type: string
          enum:
          - In
          - Out
          - Self
          - Unknown
        functionMeta:
          $ref: '#/components/schemas/FunctionMeta'
    AddressInfo:
      required:
      - address
      - isContract
      - isProxy
      - isVerified
      type: object
      properties:
        address:
          type: string
        name:
          type: string
        isContract:
          type: boolean
        isVerified:
          type: boolean
        isProxy:
          type: boolean
        verifiedStatus:
          type: string
          enum:
          - Partial
          - Full
        contractType:
          type: string
          enum:
          - contract
          - nft
          - token
    PagingModel:
      required:
      - direction
      - page
      - size
      - sort
      - totalElements
      type: object
      properties:
        page:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        sort:
          type: string
        direction:
          type: string
          enum:
          - ASC
          - DESC
        totalElements:
          type: integer
          format: int64
    LatestInternalTransactionModel:
      required:
      - data
      - paging
      type: object
      properties:
        paging:
          $ref: '#/components/schemas/PagingModel'
        data:
          type: array
          items:
            $ref: '#/components/schemas/InternalTransactionRowModel'
    FindInternalTransactionsQuery:
      required:
      - direction
      - page
      - size
      - sort
      type: object
      properties:
        page:
          minimum: 0
          type: integer
          format: int32
        size:
          maximum: 100
          minimum: 1
          type: integer
          format: int32
        direction:
          type: string
          enum:
          - ASC
          - DESC
        sort:
          type: string
          enum:
          - blockNumber
          - timestampISO
          - parentHash
          - parentFrom
          - parentTo
          - transactionType
          - from
          - to
          - direction
        filter:
          type: string
externalDocs:
  description: Chainlens Documentation
  url: https://docs.chainlens.com/
